## What is TensorFlow?

* An open source numerical computation library from Google
* Computations are repersented in the form of a data flow graph
* Targetted primarily for deep learning applications

## How does it work

* Computations represented in the form of a dataflow graph
* Each node in the graph represents mathematical opeartions (also called Ops)
* Each edge between two nodes represent the flow of data between them
* The edges carry data in the form of tensors

## What are Tensors

An array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.The number of axes or dimenstions of a tensor is called its **rank** (not the same as the matrix rank). Tensors also have a shape and type associated with them. The shape tells us about the dimensionality for each axes. The type of the tensor tells us the type of the values stored (it is similar to the dtype in Numpy arrrasy).





* A scalar is a tensor with rank 0
* A vector is a tensor with rank 1 - ```[1, 2, 5, 10]```
* A matrix is a tensor with rank 2 - ```[[1,2,3], [4,5,6]]```

### Example of a tensor with rank 3

In [1]:
import numpy as np
np.random.random(size=(2,2,2))


array([[[ 0.94664474,  0.01851108],
        [ 0.38778716,  0.83354813]],

       [[ 0.18409358,  0.82921094],
        [ 0.2964179 ,  0.02957088]]])

## TensorFlow Ops

Nodes in the tensorflow computational graph are called Ops. Each Op can take zero or more tensors as its input, perform some computation and return zero or more tensors as its output

In [2]:
import tensorflow as tf
s = tf.InteractiveSession()
a = tf.ones((2, 2))
b = tf.random_normal((2,2))

In [3]:
add = tf.add(a, b)
print(add.eval())

sub = tf.sub(a, b)
print(sub.eval())

mul = tf.mul(a, b)
print(mul.eval())

zeros = tf.zeros(shape=(3))
print(zeros.eval())

ones = tf.ones(shape=(3, 3))
print(ones.eval())



[[ 2.31956816 -0.73275125]
 [ 2.32252359  0.41596764]]
[[ 0.92365468  1.21305847]
 [ 1.21641445  1.85243404]]
[[-0.59276932  0.0529331 ]
 [-2.15010715 -1.83976769]]
[ 0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


## Constants and Variables in TensorFlow

In [4]:

const1 = tf.constant(1, name='const1')
print(const1.eval())


1


In [5]:
var1 = tf.Variable(tf.ones(10), name='var1')
s.run(tf.initialize_all_variables())
print(var1.eval())
s.close()


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


## Understanding the Computational Graph in TensorFlow

In [11]:
W = tf.Variable(tf.random_uniform(shape=[10, 1]), name='weights')
X = tf.Variable(tf.random_normal(shape=[10, 10]), name='inputs')
b = tf.constant(1.0, name='bias')
y  = tf.matmul(X, W) + b


In [12]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(y))
    
    

[[ 3.08249402]
 [-1.01846361]
 [ 1.7213757 ]
 [-0.60330451]
 [ 3.0793736 ]
 [ 1.70602655]
 [ 0.48253602]
 [-0.60385585]
 [-1.02587843]
 [-1.29599142]]


![TensorFlow computation graph](imgs/tf_graph.jpg)

## Sessions in TensorFlow

TensorFlow computational graph is an abstract entity in itself, sessions provide the context in which to run them. If you think of the graph as representing an equation with X and Y variables, the session lets you substitute X and Y with actual values and compute the result of the equation.


In [8]:
tf.reset_default_graph()


In [9]:
X = tf.placeholder(tf.float32, shape=1, name='X')
Y = tf.placeholder(tf.float32, shape=1, name='Y')
b = tf.constant(1.0)
W = X * Y + b

In [10]:
with tf.Session() as sess:
    print(sess.run(W, feed_dict={X: [10.0], Y: [2.0]}))

[ 21.]


## Scopes in TensorFlow

Scopes are like namespaces for the variables in TensorFlow. It allows us to more conveniently abstract our computational graph. If you don't use any scope, the variables are part of the global namespace and within a large enough graph, clashes might happen.

In [55]:
tf.reset_default_graph()

In [56]:
var1 = tf.Variable([1.], name='var1')

In [57]:
with tf.variable_scope('scope1'):
    var2 = tf.get_variable(name='var2', shape=[1], initializer=tf.random_normal_initializer())


In [58]:
[op.name for op in tf.get_default_graph().get_operations()]

['var1/initial_value',
 'var1',
 'var1/Assign',
 'var1/read',
 'scope1/var2',
 'scope1/var2/Initializer/random_normal/shape',
 'scope1/var2/Initializer/random_normal/mean',
 'scope1/var2/Initializer/random_normal/stddev',
 'scope1/var2/Initializer/random_normal/RandomStandardNormal',
 'scope1/var2/Initializer/random_normal/mul',
 'scope1/var2/Initializer/random_normal',
 'scope1/var2/Assign',
 'scope1/var2/read']